# Use the official Jenkins LTS image as a base
FROM jenkins/jenkins:lts

# Skip the initial setup wizard
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# Copy plugins list
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install listed plugins
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Expose the default Jenkins port
EXPOSE 8080

# Expose the port for attached slave agents
EXPOSE 50000

# Start Jenkins
CMD ["jenkins.sh"]
