# Use the official Tomcat image from Docker Hub
FROM tomcat:latest

# Copy the custom tomcat-users.xml to the container
COPY tomcat-users.xml /usr/local/tomcat/conf/

# Copy the custom entrypoint script to the container
COPY entrypoint.sh /usr/local/bin/

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint script as the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Expose the default Tomcat port
EXPOSE 8080
