# Start with the official Jenkins image
FROM jenkins/jenkins:lts

# Switch to the root user to install additional tools
USER root

# Install Maven
ARG MAVEN_VERSION=3.9.5
RUN curl -fsSL https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar xz -C /opt/ \
    && ln -s /opt/apache-maven-${MAVEN_VERSION} /opt/maven

# Set environment variables for Maven
ENV MAVEN_HOME /opt/maven
ENV PATH $MAVEN_HOME/bin:$PATH

# Additional installations or configurations can go here

# Switch back to the Jenkins user
USER jenkins

# Inform Docker that the container is listening on port 8080
EXPOSE 8080

# Start the Jenkins server
CMD ["/usr/local/bin/jenkins.sh"]
